name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: [ 'android/**' ]

defaults:
  run:
    working-directory: ./android

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run app unit tests with Gradle
      run: ./gradlew app:testDebugUnitTest
